### ISSUE TITLE
Still alive

### ISSUE THREAD

**Issue by reitzmichnicht** [arquillian/arquillian-universe-bom#99]
Hi

I'm a big fan of this BOM, but is it still alive? Are pull requests welcome to get an updated version of the bom?

Kind regards,
Michael

**Comment by Tibor17** [comment]
@MatousJobanek 
What is the situation in this project?
Would you continue with new release despite a new EE project Jakarta?

**Comment by bartoszmajsak** [comment]
Hi @Tibor17 what do you need in the release? Just updated versions on our side?

**Comment by bartoszmajsak** [comment]
Hi @reitzmichnicht 

> I'm a big fan of this BOM, but is it still alive? Are pull requests welcome to get an updated version of the bom?

Glad to hear you are fan of this little thing :) We try to automate as much as we can with dependabot as far as dependency updates are concerned. Of course all the PRs are welcome.

**Comment by Tibor17** [comment]
>> Just updated versions on our side?

No, I just want to know if the committers mean this project seriously still after one year. The reason for my remark is the fact that I scare that Arquillian is not maintained due to new Java EE is in Jakarta. And thus I am uncertain about this project, activities, interest in EE.
Can you post some roadmap what would happen with Arquillian? Would it migrate to Jakarta EE API? Will we have a new Arquillian based on Jakarta EE or we will have both (Jakarta and Java EE)?

**Comment by Tibor17** [comment]
@reitzmichnicht 
Pls close this issue. The project has cut several release versions.
